// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// GetAlbumByID provides a mock function with given fields: c
func (_m *Controller) GetAlbumByID(c *gin.Context) {
	_m.Called(c)
}

// Controller_GetAlbumByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumByID'
type Controller_GetAlbumByID_Call struct {
	*mock.Call
}

// GetAlbumByID is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Controller_Expecter) GetAlbumByID(c interface{}) *Controller_GetAlbumByID_Call {
	return &Controller_GetAlbumByID_Call{Call: _e.mock.On("GetAlbumByID", c)}
}

func (_c *Controller_GetAlbumByID_Call) Run(run func(c *gin.Context)) *Controller_GetAlbumByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Controller_GetAlbumByID_Call) Return() *Controller_GetAlbumByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *Controller_GetAlbumByID_Call) RunAndReturn(run func(*gin.Context)) *Controller_GetAlbumByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumList provides a mock function with given fields: c
func (_m *Controller) GetAlbumList(c *gin.Context) {
	_m.Called(c)
}

// Controller_GetAlbumList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumList'
type Controller_GetAlbumList_Call struct {
	*mock.Call
}

// GetAlbumList is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Controller_Expecter) GetAlbumList(c interface{}) *Controller_GetAlbumList_Call {
	return &Controller_GetAlbumList_Call{Call: _e.mock.On("GetAlbumList", c)}
}

func (_c *Controller_GetAlbumList_Call) Run(run func(c *gin.Context)) *Controller_GetAlbumList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Controller_GetAlbumList_Call) Return() *Controller_GetAlbumList_Call {
	_c.Call.Return()
	return _c
}

func (_c *Controller_GetAlbumList_Call) RunAndReturn(run func(*gin.Context)) *Controller_GetAlbumList_Call {
	_c.Call.Return(run)
	return _c
}

// PostAlbum provides a mock function with given fields: c
func (_m *Controller) PostAlbum(c *gin.Context) {
	_m.Called(c)
}

// Controller_PostAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostAlbum'
type Controller_PostAlbum_Call struct {
	*mock.Call
}

// PostAlbum is a helper method to define mock.On call
//   - c *gin.Context
func (_e *Controller_Expecter) PostAlbum(c interface{}) *Controller_PostAlbum_Call {
	return &Controller_PostAlbum_Call{Call: _e.mock.On("PostAlbum", c)}
}

func (_c *Controller_PostAlbum_Call) Run(run func(c *gin.Context)) *Controller_PostAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Controller_PostAlbum_Call) Return() *Controller_PostAlbum_Call {
	_c.Call.Return()
	return _c
}

func (_c *Controller_PostAlbum_Call) RunAndReturn(run func(*gin.Context)) *Controller_PostAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
